#!/bin/bash

# Main menu
main_menu() {
    wofi --dmenu \
        -L 6 -l 3 -W 200 -x -0 -y 10 \
        --prompt "Power Menu" \
        --hide-search \
	--hide-scroll \
	--cache-file /dev/null \
        -D allow_images=false \
	-D single_click=true \
        -D allow_reorder=false <<EOF
Shutdown
Reboot
Log off
Sleep
Lock
Cancel
EOF
}

# Confirmation menu
confirm_menu() {
    wofi --dmenu \
	--columns=2 \
	--lines=1 \
        --width 220 \
        --location center \
        --hide-search \
	--hide-scroll \
	--cache-file /dev/null \
	-D dynamic_lines=false \
        -D allow_images=false \
	-D single_click=true \
        -D allow_reorder=false <<EOF
Yes
Cancel
EOF
}

choice=$(main_menu)

case "$choice" in
    Shutdown)
        [ "$(confirm_menu)" = "Yes" ] && systemctl poweroff
        ;;
    Reboot)
        [ "$(confirm_menu)" = "Yes" ] && systemctl reboot
        ;;
    "Log off")
        [ "$(confirm_menu)" = "Yes" ] && hyprctl dispatch exit
        ;;
    Sleep)
        systemctl suspend
        ;;
    Lock)
        hyprlock
        ;;
esac
