background #0f0f0f
foreground #e8e8e8

color0  #0f0f0f
color1  #888888
color2  #e0e0e0
color3  #999999
color4  #666666
color5  #888888
color6  #aaaaaa
color7  #e8e8e8

color8  #3a3a3a
color9  #aaaaaa
color10 #ffffff
color11 #cccccc
color12 #999999
color13 #bbbbbb
color14 #dddddd
color15 #ffffff
