include colors.conf

font_family      Fira Code
font_size        11.0

background_opacity 0.5
dynamic_title    yes

window_padding_width 8
input_delay          0
tab_bar_min_tabs     2

# Shift+Enter sends ESC+CR (matches alacritty binding)
map shift+return send_text all \x1b\r
