#!/bin/bash

THEME="$HOME/.config/rofi/powermenu.rasi"

main_menu() {
    printf "Shutdown\nReboot\nLog off\nSleep\nLock\nCancel" | \
    rofi -dmenu \
        -theme-str 'mainbox { children: [ listview ]; }'\
	-hover-select \
	-me-select-entry '' \
	-me-accept-entry 'MousePrimary' \
        -lines 6 \
        -width 200 \
        -location 3 \
        -xoffset -0 \
        -yoffset 10 \
        -no-fixed-num-lines \
        -theme "$THEME" \
        -theme-str 'listview { columns: 1; lines: 6; }' \
        -theme-str 'window { width: 200px; }'
}

confirm_menu() {
    local action="$1"
    echo "$action"
    printf "Yes\nCancel" | \
    rofi -dmenu \
        -p "$action?" \
	-theme-str 'mainbox { children: [inputbar, listview ]; }' \
	-hover-select \
	-me-select-entry '' \
	-me-accept-entry 'MousePrimary' \
        -lines 1 \
        -no-fixed-num-lines \
        -theme "$THEME" \
        -theme-str 'listview { columns: 2; lines: 1; }' \
        -theme-str 'window { width: 220px; }'
}

choice=$(main_menu)

case "$choice" in
    Shutdown)
        [ "$(confirm_menu 'Shutdown')" = "Yes" ] && systemctl poweroff
        ;;
    Reboot)
        [ "$(confirm_menu 'Reboot')" = "Yes" ] && systemctl reboot
        ;;
    "Log off")
        [ "$(confirm_menu 'Log off')" = "Yes" ] && hyprctl dispatch exit
        ;;
    Sleep)
        systemctl suspend
        ;;
    Lock)
        hyprlock
        ;;
    Cancel|"")
        exit 0
        ;;
esac
