
[colors]
primary.background = "#1a1f2b"  # deep midnight blue
primary.foreground = "#d7e6f0"  # pale moonlight grey

normal.black   = "#1a1f2b"
normal.red     = "#7a8c99"  # muted slate grey-blue
normal.green   = "#a1b8d7"  # soft sky blue
normal.yellow  = "#c5d4e8"  # very light blue-grey
normal.blue    = "#5f7ea3"  # cool steel blue
normal.magenta = "#8598b0"  # muted periwinkle
normal.cyan    = "#89a6c3"  # pale blue-grey
normal.white   = "#d7e6f0"  # pale moonlight grey

bright.black   = "#3d445a"  # stormy blue-grey
bright.red     = "#9aa9b8"  # light slate
bright.green   = "#c2d0e6"  # light pastel blue
bright.yellow  = "#dce6f4"  # very pale icy blue
bright.blue    = "#7d93b2"  # calm blue
bright.magenta = "#a3b0c5"  # soft periwinkle
bright.cyan    = "#b3c4db"  # pastel blue
bright.white   = "#f0f7fd"  # soft white-blue

[window]
opacity = 0.5
