[colors]
# Background & Foreground
primary.background = "#3b2236"  # Deep muted plum-purple (keep original)
primary.foreground = "#f0c8cc"  # Soft pale sakura pink, readable

# Normal colors
normal.black   = "#3b2236"      # Same as background
normal.red     = "#d57b8b"      # Brighter sakura pink
normal.green   = "#8fb58f"      # Soft sage green, more contrast
normal.yellow  = "#e0c28f"      # Creamy warm yellow
normal.blue    = "#9b8fc1"      # Light muted violet, sakura night accent
normal.magenta = "#f0c8cc"      # Pale pink matching foreground
normal.cyan    = "#8ac1b0"      # Light muted teal for readability
normal.white   = "#f0c8cc"      # Same as foreground

# Bright colors
bright.black   = "#55435a"      # Darker plum for subtle highlights
bright.red     = "#f19fb0"      # Soft bright pink, sakura blossoms
bright.green   = "#b0d0b0"      # Light pastel green, readable
bright.yellow  = "#f7e4b5"      # Soft cream, gentle highlight
bright.blue    = "#b7aee0"      # Light violet, pops against dark background
bright.magenta = "#f0c8cc"      # Light sakura pink, harmonious
bright.cyan    = "#a7d0c9"      # Muted teal with more contrast
bright.white   = "#f8dee0"      # Very pale sakura highlight

[window]
opacity = 0.5
