background #2a003d
foreground #ffb7ff

color0  #2a003d
color1  #ff66cc
color2  #00ffcc
color3  #ffed66
color4  #cc33ff
color5  #ff4dff
color6  #33ffff
color7  #ffb7ff

color8  #53007f
color9  #ff99e6
color10 #66fff2
color11 #fff966
color12 #d27fff
color13 #ff66ff
color14 #66ffff
color15 #ffffff
